files:
- id: 3daa3de93637
  filename: 6fd1d5ad1cbf0349ce6d2bdeb9609dd0.jpg
  path: /Users/danieltwine/Documents/Coding Projects/dloper/dloperOS/dloper-os-pro/backend/data/files/3daa3de93637/6fd1d5ad1cbf0349ce6d2bdeb9609dd0.jpg
  password_hash: null
  password_protected: false
  max_downloads: null
  expires_at: null
  download_count: 0
  owner: admin
  share_url: http://localhost:8000/share/3daa3de93637
  created_at: '2025-11-26T18:15:01.605716'
  active: true
- id: 3ea9b05b1416
  filename: 62f21e9356af1dfbc16895ab004d1eb9.jpg
  path: /Users/danieltwine/Documents/Coding Projects/dloper/dloperOS/dloper-os-pro/backend/data/files/3ea9b05b1416/62f21e9356af1dfbc16895ab004d1eb9.jpg
  password_hash: pbkdf2$390000$CBftDsztvNpeuLWDd/PViQ==$wRrM2+vFAJODG7I0++s0GAZb3Dguv/MzmRnZqGKz/j4=
  password_protected: true
  max_downloads: null
  expires_at: null
  download_count: 0
  owner: admin
  share_url: http://localhost:8000/share/3ea9b05b1416
  created_at: '2025-11-26T18:17:03.870230'
  active: true
