instance:
  name: DloperOS Pro
  base_url: http://localhost:8000
security:
  secret_key: 305f6336d6d38518cad977f51340b387ccc9367750d1e5518a7856e51afe342c
  token_expiry_minutes: 90
analytics:
  enabled: true
