instance:
  name: DloperOS Pro
  base_url: http://localhost:8000
security:
  secret_key: 7f5cc68cb6c48dd16819e763a11cec3b9147e6454b1cfe1231066b2063e6886f
  token_expiry_minutes: 90
analytics:
  enabled: true
